% Properties for: Hydrogen
has_property(hydrogen, atomicNumber, 1).
has_property(hydrogen, atomicMass, 1.00).
has_property(hydrogen, color, [colorless]).
has_property(hydrogen, oxidationStates, [-1, +1]).
has_property(hydrogen, symbol, h).
has_property(hydrogen, stateOfMatter, gas).
has_property(hydrogen, density, 0.00008988).
has_property(hydrogen, meltingPoint, -259.34).
has_property(hydrogen, boilingPoint, -252.87).
has_property(hydrogen, thermalConductivity, low_(insulator)).
has_property(hydrogen, electricalConductivity, low_(insulator)).
has_property(hydrogen, crystalStructure, hcp).
has_property(hydrogen, toxicity, no).
has_property(hydrogen, reactivity, highly_reactive).
has_property(hydrogen, oxideAcidityBasicity, amphoteric).
has_property(hydrogen, reactionWithOxygen, forms_oxides).
has_property(hydrogen, reactionWithWater, no_reaction).
has_property(hydrogen, reactionWithAcids, no_reaction).
has_property(hydrogen, magnetism, diamagnetic).
has_property(hydrogen, flameTestColor, pale_blue).
has_property(hydrogen, isotopeCount, 3).
has_property(hydrogen, allotropeCount, 2).
has_property(hydrogen, corrosionResistance, n/a).
has_property(hydrogen, refractiveIndex, 1).
has_property(hydrogen, hardness, n/a).
has_property(hydrogen, radioactivity, no).
has_property(hydrogen, group, 1).
has_property(hydrogen, period, 1).
has_property(hydrogen, ionizationEnergy, 13.598).
has_property(hydrogen, electronegativity, 2.3).
has_property(hydrogen, electronConfiguration, '1s1').

% Properties for: Helium
has_property(helium, atomicNumber, 2).
has_property(helium, atomicMass, 4.00).
has_property(helium, color, [colorless]).
has_property(helium, oxidationStates, [0]).
has_property(helium, symbol, he).
has_property(helium, stateOfMatter, gas).
has_property(helium, density, 0.0001785).
has_property(helium, meltingPoint, -272.2).
has_property(helium, boilingPoint, -268.93).
has_property(helium, thermalConductivity, low_(insulator)).
has_property(helium, electricalConductivity, low_(insulator)).
has_property(helium, crystalStructure, hcp).
has_property(helium, toxicity, no).
has_property(helium, reactivity, inert).
has_property(helium, oxideAcidityBasicity, not_applicable).
has_property(helium, reactionWithOxygen, does_not_react).
has_property(helium, reactionWithWater, no_reaction).
has_property(helium, reactionWithAcids, no_reaction).
has_property(helium, magnetism, diamagnetic).
has_property(helium, flameTestColor, n/a).
has_property(helium, isotopeCount, 9).
has_property(helium, allotropeCount, 3).
has_property(helium, corrosionResistance, low_general_reactivity).
has_property(helium, refractiveIndex, 1).
has_property(helium, hardness, n/a).
has_property(helium, radioactivity, no).
has_property(helium, group, 2).
has_property(helium, period, 1).
has_property(helium, ionizationEnergy, 24.587).
has_property(helium, electronegativity, 4.16).
has_property(helium, electronConfiguration, '1s2').

